KEYCLOAK-19292 Add missing metadata to fix quarkus dev ui rendering
This allows to open http://localhost:8080/q/dev/ without problems.

Previously opening the /q/dev UI resulted in an Exception being thrown.
```
io.quarkus.qute.TemplateException: Property "description" not found on the base object "java.util.LinkedHashMap" in expression {it.description} in template tags/nonActionableExtension.html on line 21
```